# Generated by sila2.code_generator; sila2.__version__: 0.14.0

from typing import Optional
from uuid import UUID, uuid4

from sila2.server import SilaServer

from .config import Config
from .feature_implementations.robotservice_impl import RobotServiceImpl
from .feature_implementations.taskservice_impl import TaskServiceImpl
from .feature_implementations.variableservice_impl import VariableServiceImpl
from .generated.robotservice import RobotServiceFeature
from .generated.taskservice import TaskServiceFeature
from .generated.variableservice import VariableServiceFeature


class Server(SilaServer):
    def __init__(
        self,
        config: Config,
        server_uuid: Optional[UUID] = None,
        name: Optional[str] = None,
        description: Optional[str] = None,
    ):
        # Controller/task/server settings, read by the feature implementations
        # via ``self.parent_server.config``.
        self.config = config

        if name is None:
            name = "b-CAP SiLA2 Server"
        if description is None:
            description = (
                "Stateless SiLA 2 server that exposes DENSO robot controller "
                "functionality over the ORiN b-CAP protocol (via the orin_bcap "
                "client). It provides reading and writing of controller variables "
                "(including I/O) and single-shot execution of controller tasks, as "
                "well as listing of the available variable and task names. The "
                "server is stateless: each command opens a b-CAP connection, "
                "performs the operation, and disconnects, so no session state is "
                "kept between commands. Controller connection parameters (host, "
                "port, timeout, controller type - default RC9 - provider and "
                "options) are supplied at startup via a TOML configuration file."
            )
        super().__init__(
            server_name=name,
            server_description=description,
            server_type="BcapSila2Server",
            server_version="0.1.0",
            server_vendor_url="https://example.com",
            server_uuid=server_uuid if server_uuid is not None else uuid4(),
        )

        self.taskservice = TaskServiceImpl(self)
        self.set_feature_implementation(TaskServiceFeature, self.taskservice)

        self.variableservice = VariableServiceImpl(self)
        self.set_feature_implementation(VariableServiceFeature, self.variableservice)

        self.robotservice = RobotServiceImpl(self)
        self.set_feature_implementation(RobotServiceFeature, self.robotservice)
