# Generated by sila2.code_generator; sila2.__version__: 0.14.0
from __future__ import annotations

from typing import TYPE_CHECKING

from orinexception import ORiNException
from sila2.server import MetadataDict

from ..bcap import RobotUnavailableError, get_cartesian_position, get_joint_angles
from ..generated.robotservice import (
    ControllerConnectionError,
    GetCartesianPosition_Responses,
    GetJointAngles_Responses,
    RobotAccessError,
    RobotServiceBase,
)

if TYPE_CHECKING:
    from ..server import Server


class RobotServiceImpl(RobotServiceBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)

    def GetJointAngles(self, *, metadata: MetadataDict) -> GetJointAngles_Responses:
        cfg = self.parent_server.config.controller
        try:
            angles = get_joint_angles(cfg)
        except OSError as e:
            raise ControllerConnectionError(str(e))
        except (ORiNException, RobotUnavailableError) as e:
            raise RobotAccessError(str(e))
        return GetJointAngles_Responses(JointAngles=angles)

    def GetCartesianPosition(self, *, metadata: MetadataDict) -> GetCartesianPosition_Responses:
        cfg = self.parent_server.config.controller
        try:
            position = get_cartesian_position(cfg)
        except OSError as e:
            raise ControllerConnectionError(str(e))
        except (ORiNException, RobotUnavailableError) as e:
            raise RobotAccessError(str(e))
        return GetCartesianPosition_Responses(Position=position)
