# Generated by sila2.code_generator; sila2.__version__: 0.14.0
from __future__ import annotations

from datetime import timedelta
from typing import TYPE_CHECKING

from orinexception import ORiNException
from sila2.server import MetadataDict, ObservableCommandInstance

from ..bcap import (
    TaskAbnormalStopError,
    TaskTimeoutError,
    get_task_names,
    run_task,
)
from ..generated.taskservice import (
    ControllerConnectionError,
    GetTaskNames_Responses,
    RunTask_Responses,
    TaskAccessError,
    TaskExecutionTimeout,
    TaskServiceBase,
)

if TYPE_CHECKING:
    from ..server import Server

# Task start mode: 1 = one-cycle execution (run once and stop).
_ONE_CYCLE = 1
# Extra margin added to the worst-case run time when sizing the command instance
# lifetime, so a result stays retrievable a little after the longest possible run.
_LIFETIME_MARGIN = timedelta(minutes=1)


class TaskServiceImpl(TaskServiceBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)

        # Keep the command instance (and its result) retrievable for at least the
        # worst-case run time. completion_timeout 0 means "wait indefinitely", in
        # which case the instance lives until server shutdown (None).
        task_cfg = parent_server.config.task
        if task_cfg.completion_timeout_seconds > 0:
            worst_case = task_cfg.start_timeout_seconds + task_cfg.completion_timeout_seconds
            self.RunTask_default_lifetime_of_execution = (
                timedelta(seconds=worst_case) + _LIFETIME_MARGIN
            )
        else:
            self.RunTask_default_lifetime_of_execution = None

    def GetTaskNames(self, *, metadata: MetadataDict) -> GetTaskNames_Responses:
        cfg = self.parent_server.config.controller
        try:
            names = get_task_names(cfg)
        except (OSError, ORiNException) as e:
            raise ControllerConnectionError(str(e))
        return GetTaskNames_Responses(TaskNames=list(names))

    def RunTask(
        self, TaskName: str, *, metadata: MetadataDict, instance: ObservableCommandInstance
    ) -> RunTask_Responses:
        config = self.parent_server.config
        task_cfg = config.task

        # The command stays `waiting` until the task is observed running; run_task
        # calls begin_execution (on_running) once the task reaches TASK_RUN. The
        # task duration is indeterminate, so progress / estimated remaining time
        # are left unset (None) rather than fabricated.
        try:
            run_task(
                config.controller,
                TaskName,
                mode=_ONE_CYCLE,
                poll_interval=task_cfg.poll_interval_seconds,
                start_timeout=task_cfg.start_timeout_seconds,
                completion_timeout=task_cfg.completion_timeout_seconds,
                on_running=instance.begin_execution,
            )
        except OSError as e:
            raise ControllerConnectionError(str(e))
        except TaskTimeoutError as e:
            raise TaskExecutionTimeout(str(e))
        except (ORiNException, TaskAbnormalStopError) as e:
            raise TaskAccessError(str(e))

        instance.progress = 1.0
        return RunTask_Responses(Started=True)
