# Generated by sila2.code_generator; sila2.__version__: 0.14.0
from __future__ import annotations

import time
from datetime import timedelta
from typing import TYPE_CHECKING

from orinexception import ORiNException
from sila2.server import MetadataDict, ObservableCommandInstance

from ..bcap import get_task_names, start_task
from ..generated.taskservice import (
    ControllerConnectionError,
    GetTaskNames_Responses,
    RunTask_Responses,
    TaskAccessError,
    TaskServiceBase,
)

if TYPE_CHECKING:
    from ..server import Server

# Task start mode: 1 = one-cycle execution (run once and stop).
_ONE_CYCLE = 1


class TaskServiceImpl(TaskServiceBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)

        # Default lifetime of observable command instances.
        self.RunTask_default_lifetime_of_execution = timedelta(minutes=30)

    def GetTaskNames(self, *, metadata: MetadataDict) -> GetTaskNames_Responses:
        cfg = self.parent_server.config.controller
        try:
            names = get_task_names(cfg)
        except (OSError, ORiNException) as e:
            raise ControllerConnectionError(str(e))
        return GetTaskNames_Responses(TaskNames=list(names))

    def RunTask(
        self, TaskName: str, *, metadata: MetadataDict, instance: ObservableCommandInstance
    ) -> RunTask_Responses:
        config = self.parent_server.config

        # set execution status from `waiting` to `running`
        instance.begin_execution()

        try:
            start_task(config.controller, TaskName, mode=_ONE_CYCLE)
        except OSError as e:
            raise ControllerConnectionError(str(e))
        except ORiNException as e:
            raise TaskAccessError(str(e))

        # v1: completion detection is not implemented yet. Wait a fixed interval
        # after starting the task before completing the command. The observable
        # form is kept so real completion detection can replace this later.
        time.sleep(config.task.run_wait_seconds)

        return RunTask_Responses(Started=True)
