# Generated by sila2.code_generator; sila2.__version__: 0.14.0
from __future__ import annotations

from typing import TYPE_CHECKING

from sila2.server import MetadataDict

from ..generated.variableservice import (
    GetVariableNames_Responses,
    ReadVariable_Responses,
    VariableDataType,
    VariableServiceBase,
    WriteVariable_Responses,
)

if TYPE_CHECKING:
    from ..server import Server


class VariableServiceImpl(VariableServiceBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)

    def ReadVariable(self, VariableName: str, *, metadata: MetadataDict) -> ReadVariable_Responses:
        raise NotImplementedError  # TODO

    def WriteVariable(
        self, VariableName: str, Value: str, DataType: VariableDataType, *, metadata: MetadataDict
    ) -> WriteVariable_Responses:
        raise NotImplementedError  # TODO

    def GetVariableNames(self, *, metadata: MetadataDict) -> GetVariableNames_Responses:
        raise NotImplementedError  # TODO
