# Generated by sila2.code_generator; sila2.__version__: 0.14.0
from __future__ import annotations

from typing import TYPE_CHECKING, Any, Tuple

from orinexception import ORiNException
from sila2.server import MetadataDict

from ..bcap import get_variable_names, read_variable, write_variable
from ..generated.variableservice import (
    ControllerConnectionError,
    DataTypeConversionError,
    GetVariableNames_Responses,
    ReadVariable_Responses,
    VariableAccessError,
    VariableDataType,
    VariableServiceBase,
    WriteVariable_Responses,
)

if TYPE_CHECKING:
    from ..server import Server

# Supported data types (see the VariableDataType definition in the feature).
_INTEGER = "Integer"
_REAL = "Real"
_BOOLEAN = "Boolean"
_STRING = "String"

_TRUE_LITERALS = {"true", "1", "yes", "on"}
_FALSE_LITERALS = {"false", "0", "no", "off"}


def _to_sila_value(value: Any) -> Tuple[str, VariableDataType]:
    """Convert a native b-CAP value to a (string, data type) pair."""
    # bool must be checked before int (bool is a subclass of int).
    if isinstance(value, bool):
        return ("True" if value else "False"), _BOOLEAN
    if isinstance(value, int):
        return str(value), _INTEGER
    if isinstance(value, float):
        return str(value), _REAL
    if isinstance(value, str):
        return value, _STRING
    raise VariableAccessError(
        f"Unsupported variable value type for v1: {type(value).__name__}"
    )


def _parse_bool(value: str) -> bool:
    lowered = value.strip().lower()
    if lowered in _TRUE_LITERALS:
        return True
    if lowered in _FALSE_LITERALS:
        return False
    raise ValueError(f"not a boolean literal: {value!r}")


def _from_sila_value(value: str, data_type: VariableDataType) -> Any:
    """Convert a (string, data type) pair to the native value to write."""
    try:
        if data_type == _INTEGER:
            return int(value)
        if data_type == _REAL:
            return float(value)
        if data_type == _BOOLEAN:
            return _parse_bool(value)
        if data_type == _STRING:
            return value
    except (ValueError, TypeError) as e:
        raise DataTypeConversionError(f"Cannot convert {value!r} to {data_type}: {e}")
    raise DataTypeConversionError(f"Unknown data type: {data_type!r}")


class VariableServiceImpl(VariableServiceBase):
    def __init__(self, parent_server: Server) -> None:
        super().__init__(parent_server=parent_server)

    def ReadVariable(self, VariableName: str, *, metadata: MetadataDict) -> ReadVariable_Responses:
        cfg = self.parent_server.config.controller
        try:
            value = read_variable(cfg, VariableName)
        except OSError as e:
            raise ControllerConnectionError(str(e))
        except ORiNException as e:
            raise VariableAccessError(str(e))
        str_value, data_type = _to_sila_value(value)
        return ReadVariable_Responses(Value=str_value, DataType=data_type)

    def WriteVariable(
        self, VariableName: str, Value: str, DataType: VariableDataType, *, metadata: MetadataDict
    ) -> WriteVariable_Responses:
        cfg = self.parent_server.config.controller
        native = _from_sila_value(Value, DataType)
        try:
            write_variable(cfg, VariableName, native)
        except OSError as e:
            raise ControllerConnectionError(str(e))
        except ORiNException as e:
            raise VariableAccessError(str(e))
        return WriteVariable_Responses()

    def GetVariableNames(self, *, metadata: MetadataDict) -> GetVariableNames_Responses:
        cfg = self.parent_server.config.controller
        try:
            names = get_variable_names(cfg)
        except (OSError, ORiNException) as e:
            raise ControllerConnectionError(str(e))
        return GetVariableNames_Responses(VariableNames=list(names))
